SRC=../seanhoughton.io.original
sed -i'.original' -e 's/featured_image: .*/featured_image: \/astrophotography\/the-lagoon-nebula\/teaser.jpg/g' ./content/astrophotography/the-lagoon-nebula/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/astrophotography\/m42-shot-with-a-canon-10d\/teaser.jpg/g' ./content/astrophotography/m42-shot-with-a-canon-10d/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/astrophotography\/noise-reduction-in-film-images\/teaser.jpg/g' ./content/astrophotography/noise-reduction-in-film-images/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/astrophotography\/sky-limited-exposure\/teaser.png/g' ./content/astrophotography/sky-limited-exposure/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/astrophotography\/astrophotography-equipment\/teaser.jpg/g' ./content/astrophotography/astrophotography-equipment/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/astrophotography\/adding-a-set-screw\/teaser.jpg/g' ./content/astrophotography/adding-a-set-screw/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/astrophotography\/half-moon\/teaser.jpg/g' ./content/astrophotography/half-moon/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/astrophotography\/first-light-with-the-st-8300\/teaser.jpg/g' ./content/astrophotography/first-light-with-the-st-8300/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/astrophotography\/new-scans-of-old-astrophotos\/teaser.jpg/g' ./content/astrophotography/new-scans-of-old-astrophotos/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/astrophotography\/g11-bearing-upgrade\/teaser.jpg/g' ./content/astrophotography/g11-bearing-upgrade/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/astrophotography\/5d-mark-ii-astrophotography-tests\/teaser.jpg/g' ./content/astrophotography/5d-mark-ii-astrophotography-tests/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/astrophotography\/sky-limited-exposure-script-for-pixinsight\/teaser.png/g' ./content/astrophotography/sky-limited-exposure-script-for-pixinsight/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/astrophotography\/scaled-dark-frames-in-maxim-dl-and-pixinsight\/teaser.png/g' ./content/astrophotography/scaled-dark-frames-in-maxim-dl-and-pixinsight/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/posts\/2006\/04\/09\/road-1-joel-0\/teaser.jpeg/g' ./content/posts/2006/04/09/road-1-joel-0/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/posts\/2006\/02\/19\/bootleg-canyon\/teaser.jpg/g' ./content/posts/2006/02/19/bootleg-canyon/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/posts\/2007\/09\/26\/red-bull-air-race\/teaser.jpg/g' ./content/posts/2007/09/26/red-bull-air-race/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/posts\/2007\/09\/26\/rip-scott-carter\/teaser.jpg/g' ./content/posts/2007/09/26/rip-scott-carter/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/posts\/2009\/07\/27\/ductati-1098s-bling\/teaser.png/g' ./content/posts/2009/07/27/ductati-1098s-bling/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/posts\/2010\/06\/27\/worst-phone-ever\/teaser.png/g' ./content/posts/2010/06/27/worst-phone-ever/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/posts\/2005\/03\/05\/freeriding-at-ted-williams\/teaser.jpeg/g' ./content/posts/2005/03/05/freeriding-at-ted-williams/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/posts\/2005\/05\/05\/trackday-and-ama-race-at-fontana\/teaser.jpeg/g' ./content/posts/2005/05/05/trackday-and-ama-race-at-fontana/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/posts\/2005\/02\/19\/trackday-at-california-speedway\/teaser.jpeg/g' ./content/posts/2005/02/19/trackday-at-california-speedway/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/posts\/2005\/10\/04\/trackday-at-streets-of-willow-part-ii\/teaser.jpeg/g' ./content/posts/2005/10/04/trackday-at-streets-of-willow-part-ii/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/posts\/2005\/07\/03\/trackday-at-california-speedway-2\/teaser.jpeg/g' ./content/posts/2005/07/03/trackday-at-california-speedway-2/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/posts\/2005\/07\/17\/when-youre-too-sick-to-surf-take-pictures\/teaser.jpg/g' ./content/posts/2005/07/17/when-youre-too-sick-to-surf-take-pictures/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/posts\/2005\/07\/06\/road-trip-to-canada\/teaser.jpg/g' ./content/posts/2005/07/06/road-trip-to-canada/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/posts\/2005\/07\/12\/motogp-race-at-laguna-seca\/teaser.jpeg/g' ./content/posts/2005/07/12/motogp-race-at-laguna-seca/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/posts\/2005\/07\/25\/surfing-photos-from-ponto-jetty-in-carlsbad\/teaser.jpg/g' ./content/posts/2005/07/25/surfing-photos-from-ponto-jetty-in-carlsbad/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/posts\/2005\/08\/19\/trackday-at-buttonwillow\/teaser.jpeg/g' ./content/posts/2005/08/19/trackday-at-buttonwillow/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/posts\/2004\/10\/25\/streets-of-willow\/teaser.jpeg/g' ./content/posts/2004/10/25/streets-of-willow/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/game-review-scores-part-ii\/teaser.png/g' ./content/development/game-review-scores-part-ii/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/new-gallery-integration\/teaser.png/g' ./content/development/new-gallery-integration/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/the-transformers-multiplayer-trailer-is-out\/teaser.png/g' ./content/development/the-transformers-multiplayer-trailer-is-out/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/game-review-scores-part-iii\/teaser.png/g' ./content/development/game-review-scores-part-iii/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/building-an-automated-build-and-release-server-for-pixinsight\/teaser.png/g' ./content/development/building-an-automated-build-and-release-server-for-pixinsight/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/the-transformers-xbox-360-demo-is-live\/teaser.png/g' ./content/development/the-transformers-xbox-360-demo-is-live/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/transformers-war-for-cybertron-video-game-exclusive-debut-trailer-hd-game-trailers-videos-gametrailers-com\/teaser.png/g' ./content/development/transformers-war-for-cybertron-video-game-exclusive-debut-trailer-hd-game-trailers-videos-gametrailers-com/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/finding-duplicate-images-in-aperture\/teaser.png/g' ./content/development/finding-duplicate-images-in-aperture/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/balance-and-flow-maps\/teaser.png/g' ./content/development/balance-and-flow-maps/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/plume-lightwave-plugin\/teaser.jpg/g' ./content/development/plume-lightwave-plugin/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/bad-game-developer-conference-scheduling\/teaser.png/g' ./content/development/bad-game-developer-conference-scheduling/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/avoiding-file-io-in-unit-tests\/teaser.png/g' ./content/development/avoiding-file-io-in-unit-tests/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/game-review-scores-part-i\/teaser.png/g' ./content/development/game-review-scores-part-i/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/anime-lightwave-plugin\/teaser.jpg/g' ./content/development/anime-lightwave-plugin/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/thrift-protocols-ajax-and-language-support\/teaser.png/g' ./content/development/thrift-protocols-ajax-and-language-support/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/realtime-earthquake-map\/teaser.png/g' ./content/development/realtime-earthquake-map/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/visionscape-gallery\/teaser.jpg/g' ./content/development/visionscape-gallery/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/darkwatch-has-shipped\/teaser.jpg/g' ./content/development/darkwatch-has-shipped/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/performance-optimization\/teaser.png/g' ./content/development/performance-optimization/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/transformers-behind-the-scenes\/teaser.png/g' ./content/development/transformers-behind-the-scenes/index.md
sed -i'.original' -e 's/featured_image: .*/featured_image: \/development\/using-dashboards-to-reinforce-memory-budgets\/teaser.png/g' ./content/development/using-dashboards-to-reinforce-memory-budgets/index.md