---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: '2.1'

inputs:
  - name: source
  - name: version

outputs:
  - name: site
    path: site

run:
  path: sh
  args:
  - -exc
  - |
    root=$(pwd)
    cd ${root}/source
    bundler install
    jekyll build
    version=`cat ${root}/version/version`
    cd ${root}/source/_site && tar cvzf ${root}/site/site-${version}.tgz .