---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jekyll
    tag: '3.2'

inputs:
  - name: source

outputs:
  - name: site
    path: site

run:
  path: sh
  args:
  - -exc
  - |
    cd source
    bundler install
    jekyll build --destination ../site